/// Flutter icons MyIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData down_arrow_on_shopping_basket = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash_drive = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jack_cable = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopping_list = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd_player = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
